---
- hosts: servers
  become: yes
  tasks:
    - name: Install git
      command: yum install -y git

    - name: Clone the repository
      git:
        repo: 'https://github.com/Lev2607/travel-blog.git'
        dest: /home/ec2-user/travel-blog
        force: yes

    - name: Install dependencies
      shell: |
        . /home/ec2-user/.nvm/nvm.sh
        nvm use 14.21.3
        npm install
      args:
        chdir: /home/ec2-user/travel-blog

    - name: Build the application
      shell: |
        . /home/ec2-user/.nvm/nvm.sh
        nvm use 14.21.3
        npm run build
      args:
        chdir: /home/ec2-user/travel-blog

    - name: Install PM2
      shell: |
        . /home/ec2-user/.nvm/nvm.sh
        nvm use 14.21.3
        npm install -g pm2

    - name: Start the application
      shell: |
        . /home/ec2-user/.nvm/nvm.sh
        nvm use 14.21.3
        pm2 start npm --name "my-app" -- start
      args:
        chdir: /home/ec2-user/travel-blog