---
- name: Konfiguration der Reiseblog-Anwendung
  hosts: all
  become: true
  tasks:
    - name: Klone das GitHub-Repository
      git:
        repo: https://github.com/Lev2607/travel-blog.git
        dest: /home/ubuntu/travel-blog
        force: yes

    - name: Erstellen der NGINX-Konfiguration für die Next.js-Anwendung
      template:
        src: nginx.conf.j2
        dest: /etc/nginx/nginx.conf
      notify:
        - Restart NGINX

    - name: Starten der Next.js-Anwendung
      shell: |
        cd /home/ubuntu/travel-blog/pages
        sudo npm run build
        sudo npm start
      async: 0
      poll: 0

  handlers:
    - name: Restart NGINX
      service:
        name: nginx
        state: restarted
