---
- hosts: servers
  become: yes
  vars:
    app_path: /home/ubuntu/travel-blog
  tasks:
    - name: Install git
      apt:
        name: git
        state: present

    - name: Clone the repository
      git:
        repo: 'https://github.com/Lev2607/travel-blog.git'
        dest: "{{ app_path }}"
        force: yes
      become_user: ubuntu
      ignore_errors: true

    - name: Install dependencies
      community.general.npm:
        path: "{{ app_path }}"
      become_user: ubuntu

    - name: Build the application
      community.general.npm:
        path: "{{ app_path }}"
        command: run build
      become_user: ubuntu

    - name: Add PM2 to PATH
      become_user: ubuntu
      lineinfile:
        path: ~/.profile
        line: 'export PATH=~/.npm-global/bin:$PATH'
        insertafter: EOF
      vars:
        profile_path: "~/.profile"
      when: ansible_distribution == "Ubuntu"

    - name: Start the application with PM2
      shell: /home/ubuntu/.npm-global/bin/pm2 start npm --name "my-app" -- start
      args:
        chdir: "{{ app_path }}"

    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Create nginx directory if it doesn't exist
      file:
        path: /etc/nginx
        state: directory    

    - name: Copy Nginx configuration file
      copy:
        src: travel-blog.conf
        dest: /etc/nginx/nginx.conf
      notify: Reload Nginx

  handlers:
    - name: Reload Nginx
      service:
        name: nginx
        state: reloaded    