---
- hosts: servers
  become: yes
  tasks:
    - name: Install git
      apt:
        name: git
        state: present

    - name: Clone the repository
      git:
        repo: 'https://github.com/Lev2607/travel-blog.git'
        dest: /home/ubuntu/travel-blog
        force: yes
      become_user: ubuntu

    - name: Install dependencies
      become_user: ubuntu
      shell: npm install
      args:
        chdir: /home/ubuntu/travel-blog

    - name: Build the application
      become_user: ubuntu
      shell: npm run build
      args:
        chdir: /home/ubuntu/travel-blog

    - name: Install PM2
      become_user: ubuntu
      shell: npm install -g pm2 --prefix=/usr/local

    - name: Start the application with PM2
      become_user: ubuntu
      shell: pm2 start npm --name "my-app" -- start
      args:
        chdir: /home/ubuntu/travel-blog



