---
- hosts: servers
  become: yes
  tasks:
    - name: Install git
      command: yum install -y git

    - name: Clone the repository
      git:
        repo: 'https://github.com/Lev2607/travel-blog.git'
        dest: /home/ec2-user/travel-blog
        force: yes

    - name: Install dependencies
      npm:
        path: /home/ec2-user/travel-blog

    - name: Build the application
      shell: |
        . ~/.nvm/nvm.sh
        nvm use 14.21.3
        cd /home/ec2-user/travel-blog
        npm run build
      args:
        chdir: /home/ec2-user/travel-blog

    - name: Start the application
      command: npm start
      args:
        chdir: /home/ec2-user/travel-blog